### ISSUE TITLE
[Question] Where's the data coming from?

### ISSUE THREAD

**Issue by CptMeatball** [GinoPane/oc-awesomeiconslist-plugin#1]
Just out of curiosity, how does this work? I don't see any reference to FontAwesome itself, so I'm just wondering where you're getting the complete library from.

I've worked on something similar myself, but that was based on a key-based object with all the necessary font-awesome icon names.

**Comment by GinoPane** [comment]
Hi!
Oh, it's not a secret, you can check this file: https://github.com/GinoPane/oc-awesomeiconslist-plugin/blob/feature/partials_generator/formwidgets/awesomeiconslist/bin/generate_partials.php.
