### ISSUE TITLE
Not showing up in the Formbuilder (October 2.0.23)

### ISSUE THREAD

**Issue by Alexlg89** [GinoPane/oc-awesomeiconslist-plugin#11]
### Expected behaviour
I would like to see the awesomeiconslist in the Widget List of the Form Builder.

### Actual behaviour
It does not appear in the Widget List. If i add it to the Yaml File, the Form Builder says "unknown control type: awesomeiconslist".

### Steps to reproduce the behaviour
October 2 with builder plugin. Try to add the awesomeiconslist to the form.

**Comment by Alexlg89** [comment]
It is just the form builder which shows the array. The icon list appears in the form, if i execute it. Sorry :)

**Comment by GinoPane** [comment]
No worries! :)
Glad it worked (I assume)
